### ISSUE TITLE
[BUG] select command works incorrectly

### ISSUE THREAD

**Issue by MikitaBf** [felixyeahh/fyCursor#10]
**Describe the bug**
fyCursor.select() method throws a "no such column: {column_name}FROM" error if deleting column_name column (likely it just doesn't insert a whitespace between column_name and FROM keyword). 

**To Reproduce**
1. Try to launch any program containing fyCursor.select(). 
2. Get your running program to the line with this method. 

**Expected behavior**
The select() method should've selected a value from the database and return it. So, select("column", "table") should've executed the "SELECT column FROM table" query but instead executed "SELECT columnFROM table" (without a whitespace between column name and FROM). 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Python Version [Python 3.11.4]
 - FyCursor Version [0.1.5.1]

**Additional context**
The problem appeared after one of the latest updates of fyCursor. FyCursor 0.1.3 definitely didn't have that problem.

**Comment by felixyeahh** [comment]
fixed in commit [#8fdb8b3](https://github.com/felixyeahh/fyCursor/commit/8fdb8b308f2b255cde2d0e43efdce548aed101e9)
