### ISSUE TITLE
[BUG] execute() with parameters works incorrectly

### ISSUE THREAD

**Issue by MikitaBf** [felixyeahh/fyCursor#12]
**Describe the bug**
execute(query, (param1, param2, ...,)) throws an error related to Python's replace method: __replace() argument 2 must be str, not tuple__ (likely it tries to replace the "?" characters in the query with the parameters tuple). 

**To Reproduce**
1. Call execute() method with an SQL query.
2. Provide any parameters (don't forget to put a comma after all the parameters). 

**Expected behavior**
The parameters should've been passed in the SQL query and not cause any error. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.11.4
 - Cursor Version: 0.1.5.3

**Additional context**
1. The problem appears if 1 or more params are passed.
2. Removing the comma from the end or the parameters list likely fixes the error, but instead leads to an sqlite3 operational error.

**Comment by felixyeahh** [comment]
fixed
